name: simple_pagination
description: A simple Pagination Widget for your Large list of widgets
version: 0.0.1
author: Praveen<praveen.json@gmail.com>
homepage: https://github.com/Praveen-Aanand/simple_pagination.git
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
